<?php

 echo "<h1>HOW TO CHECK DATA TYPE </h1>";
 ECHO "<HR>";
$a = 45;

var_dump ($a);

ECHO "<HR>";
$a = "45";

var_dump ($a);

ECHO "<HR>";
$a = "piyush";

var_dump ($a);

ECHO "<HR>";
$a = 45.54;

var_dump ($a);

ECHO "<HR>";
$a = "45.54";

var_dump ($a);


ECHO "<HR>";
$a = TRUE;

var_dump ($a);


ECHO "<HR>";
$a = "TRUE";

var_dump ($a);


ECHO "<HR>";
$a = NULL;

var_dump ($a);


ECHO "<HR>";
$a = ["RADHA","PIYUSH"];

var_dump ($a);
ECHO "<HR>";














?>
