<?php


echo  "<H1>THIS IS IF STATEMENT FOR PHP</H2>";
 ECHO "<HR>";
$a = 25;

if($a>=20){
    echo "YOU CAN BUY A BLUE PEN";
}
ECHO "<HR>";
ECHO "<BR>";
ECHO "<BR>";
echo "<h1><u>THIS ISIF ELESE STATEMENT</u></h1>";
ECHO "<HR>";
$a = 5;

if($a>18){
    
    echo " $a is greater than 18";
}
else {
    echo " $a is smaller than "."  : "."18";
} ECHO "<HR>";

ECHO "<BR>";
ECHO "<BR>";
echo "<h2><u>THIS IS IF ELESE IF STATEMENT</u></h2>";


$a = 25;
if($a >=18){
     echo "you can vote in election ";

}
elseif($a<18){
    echo "you can not vote in election";

}
else {
    
"write a valid nunber please ";}
echo "<br><br>";
$a = "PIYUSH<BR>";

$a.="RAHUL<BR>";
$a.="KUMAR<BR>";
echo $a;







?>