<?php

echo "<h2>THIS IS PHP DATE AND TIME FUNCTION </h2>";
echo "<hr>";

echo "<i>THIS IS PHP DATE FUNCTION</i><br><br>";

echo date("d/m/y")."<BR><BR>";

echo date("d:m:y")."<BR><BR>";

echo DATE(" D-M-Y")."<BR><BR>";

echo DATE(" D M Y");


/*d - Represent day of the month; two digits with leading zeros (01 or 31) 
D - Represent day of the week in text as an abbreviation (Mon to Sun) 
m - Represent month in numbers with leading zeros (01 or 12) 
M - Represent month in text, abbreviated (Jan to Dec) 
y - Represent year in two digits (08 or 14) 
Y - Represent year in four digits (2008 or 2014)*/

echo "<hr>";

echo "<i>THIS IS PHP TIME FUNCTION</i><br><br>";

echo date("h/i/s/a")."<br><br>";

echo date("H-i-s-A");

echo "<hr>";


















?>