<?php
ECHO "<H1>THIS IS SWITCH  STATEMENT FOR PHP</H1>";
$day = 5 ;
switch($day){


case 0:
    echo "<h1>TODAY IS SUNDAY</h1>";

break;


case 1:
    echo "<h1>TODAY IS MONDAY</h1>";

break;

case 2:
    echo "<h1>TODAY IS TUESDAY</h1>";

break;

case 3:
    echo "<h1>TODAY IS WEDNESDAY</h1>";

break;

case 4:
    echo "<h1>TODAY IS THURSDAY</h1>";

break;

case 5:
    echo "<h1>TODAY IS FRIDAY</h1>";

break;

case 6:
    echo "<h1>TODAY IS SATURDAY</h1>";

break;
default :

echo "<h1>WRITE A VALID NUMBER</h1>";

}















?>
